all: oob1 oob2 oob3 oob4 oob5

oob1: oob1.c
	gcc -o oob1 oob1.c

oob2: oob2.c
	gcc -o oob2 oob2.c

oob3: oob3.c
	gcc -o oob3 oob3.c

oob4: oob4.c
	gcc -o oob4 oob4.c

oob5: oob5.c
	gcc -o oob5 oob5.c -Wl,-z,relro,-z,now
